---
title: "Visualization Activity"
author: "Ariana Horn"
date: '2022-06-27'
output: 
html_document:
  bootswatch: morph
---
## **This document includes three graphs of the dataset 'drug use by age'**

```{r include=TRUE}
#laoding dataset 
library("readr")
urlfile="https://raw.githubusercontent.com/fivethirtyeight/data/dcafc374774f45ede5dd9b8c22ff8097b79a243c/drug-use-by-age/drug-use-by-age.csv"
#rename dataset to mydataset 
mydataset<-read_csv(url(urlfile))
```
```{r include=TRUE}
#install package for creating graphs
library("tidyverse")
#> ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
#> ✔ ggplot2 3.3.2     ✔ purrr   0.3.4
#> ✔ tibble  3.0.3     ✔ dplyr   1.0.2
#> ✔ tidyr   1.1.2     ✔ stringr 1.4.0
#> ✔ readr   1.4.0     ✔ forcats 0.5.0
#> ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
#> ✖ dplyr::filter() masks stats::filter()
#> ✖ dplyr::lag()    masks stats::lag()
```

```{r include=TRUE}
#code chunk for first graph
ggplot(data = mydataset) + 
  geom_point(mapping = aes(x = `age`, y = `alcohol-use`))   + geom_point(mapping = aes(x = `age`, y = `marijuana-use`, color = `marijuana-use`))
```
## **How many participants per age group** 
```{r include=TRUE}
#second code chunk for graph
ggplot(data = mydataset) + 
  geom_bar(mapping = aes(x = `age`, fill = `n`), position = "dodge")
```


## **Bar graph**
## *in the first graph is visual which age group is consuming more marijuana and in compare in the second you can see the visulization of alcohol use*
```{r include=TRUE}
#third code chunk for graph
#bar graph 1
bar <- ggplot(data = mydataset) + 
  geom_bar(
    mapping = aes(x = `age`, fill = `marijuana-use`), 
    show.legend = FALSE,
    width = 2
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

bar + coord_flip()
bar + coord_polar()

#bar graph 2 
bar <- ggplot(data = mydataset) + 
  geom_bar(
    mapping = aes(x = `age`, fill = `alcohol-use`), 
    show.legend = FALSE,
    width = 2
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

bar + coord_flip()
bar + coord_polar()
```
